# docs: https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-updates:
        patterns:
          - "*"  # Groups all Rust crates
      security-updates:
        update-types: ["patch", "minor"]

