[toolchain]
channel = "stable"
components = [ "rustfmt", "clippy", "llvm-tools-preview" ]

[target]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-freebsd",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
